site_name: Do Language
site_description: Documentation for the Do programming language
repo_url: https://github.com/dolang-org/dolang

hooks:
  - docs/hooks/lexer_hook.py

plugins:
  - search
  - mkdocstrings:
      default_handler: do
      handlers:
        do:
          options:
            heading_level: 2
            show_private: false
            paths:
              - dolang-shell-modules/lib/

extra_css:
  - extra.css

theme:
  name: material
  features:
    - navigation.indexes
  palette:
    scheme: slate
    primary: indigo

markdown_extensions:
  - admonition
  - footnotes
  - pymdownx.details
  - pymdownx.highlight:
      anchor_linenums: true
      default_lang: dolang
  - pymdownx.superfences

nav:
  - Home: index.md
  - Language Guide:
    - language/index.md
    - language/basic-types.md
    - language/data-structures.md
    - language/commands.md
    - language/expressions.md
    - language/strings.md
    - language/variables.md
    - language/flow-control.md
    - language/vertical-layout.md
    - language/functions.md
    - language/destructuring.md
    - language/modules.md
    - language/classes.md
    - language/error-handling.md
    - language/concurrency.md
    - language/decorators.md
    - language/misc.md
    - language/prelude.md
  - Shell Guide:
    - shell/index.md
    - shell/external-programs.md
    - shell/modules.md
    - shell/cli-tools.md
    - shell/terminal-output.md
    - shell/system-errors.md
    - shell/security.md
    - shell/vfs.md
    - shell/containers.md
    - shell/ssh.md
    - shell/wsl.md
    - shell/admin.md
  - VM Guide:
    - vm/index.md
    - vm/provisioning.md
    - vm/cloud-init.md
    - vm/windows.md
    - vm/gold-images.md
    - vm/caching.md
  - lsp.md
  - Reference:
    - admin: api/admin.md
    - args: api/args.md
    - base64: api/base64.md
    - compile:
      - api/compile/index.md
      - api/compile/annotation.md
      - api/compile/diagnostic.md
      - api/compile/note.md
      - api/compile/patch.md
      - api/compile/pos.md
      - api/compile/unit.md
      - api/compile/span.md
    - digest:
      - api/digest/index.md
      - api/digest/blake3.md
      - api/digest/md5.md
      - api/digest/sha1.md
      - api/digest/sha256.md
      - api/digest/sha512.md
      - api/digest/state.md
    - docker:
      - api/docker/index.md
      - api/docker/container.md
      - api/docker/container-exit-error.md
      - api/docker/image.md
      - api/docker/noimageerror.md
    - exec:
      - api/exec/index.md
    - fs:
      - api/fs/index.md
      - api/fs/direntry.md
      - api/fs/file.md
      - api/fs/file-lock.md
      - api/fs/fs-metadata.md
      - api/fs/metadata.md
      - api/fs/path.md
      - api/fs/xattr-entry.md
    - fs.unix:
      - api/fs/unix/index.md
      - api/fs/unix/mode.md
      - api/fs/unix/path.md
    - fs.windows:
      - api/fs/windows/index.md
      - api/fs/windows/path.md
      - api/fs/windows/stream-entry.md
    - glob:
      - api/glob/index.md
      - api/glob/glob.md
    - http:
      - api/http/index.md
      - api/http/client.md
      - api/http/error.md
      - api/http/event.md
      - api/http/response.md
      - api/http/status.md
    - http.mock:
      - api/http-mock/index.md
      - api/http-mock/mock.md
      - api/http-mock/request.md
      - api/http-mock/server.md
    - json: api/json.md
    - libvirt:
      - api/libvirt/index.md
      - api/libvirt/domain.md
      - api/libvirt/nodomainerror.md
    - load:
      - api/load/index.md
      - api/load/importhandler.md
    - patch:
      - api/patch/index.md
      - api/patch/applyerror.md
      - api/patch/parseerror.md
      - api/patch/patch.md
      - api/patch/patchiter.md
    - podman:
      - api/podman/index.md
      - api/podman/container.md
      - api/podman/container-exit-error.md
      - api/podman/image.md
      - api/podman/noimageerror.md
    - proc:
      - api/proc/index.md
      - api/proc/error.md
      - api/proc/info.md
      - api/proc/pipe-receiver.md
      - api/proc/pipe-sender.md
      - api/proc/proc.md
      - api/proc/program.md
      - api/proc/status.md
    - proc.windows: api/proc.windows.md
    - progress:
      - api/progress/index.md
      - api/progress/indicator.md
    - rand: api/rand.md
    - regex:
      - api/regex/index.md
      - api/regex/captures.md
      - api/regex/find.md
      - api/regex/match.md
      - api/regex/regex.md
    - security:
      - api/security/index.md
    - security.unix:
      - api/security/unix/index.md
      - api/security/unix/ace.md
      - api/security/unix/acl.md
      - api/security/unix/identity.md
      - api/security/unix/permission.md
    - security.nfs4:
      - api/security/nfs4/index.md
      - api/security/nfs4/ace.md
      - api/security/nfs4/acl.md
      - api/security/nfs4/flags.md
      - api/security/nfs4/mask.md
    - security.macos:
      - api/security/macos/index.md
      - api/security/macos/ace.md
      - api/security/macos/acl.md
      - api/security/macos/flags.md
      - api/security/macos/mask.md
    - security.windows:
      - api/security/windows/index.md
      - api/security/windows/access-mask.md
      - api/security/windows/ace.md
      - api/security/windows/ace-flags.md
      - api/security/windows/acl.md
      - api/security/windows/secdesc.md
      - api/security/windows/secdesc-control.md
      - api/security/windows/sec-info.md
      - api/security/windows/sid.md
      - api/security/windows/sidname.md
      - api/security/windows/tokengroup.md
      - api/security/windows/token-group-attributes.md
      - api/security/windows/tokeninfo.md
    - shell:
      - api/shell/index.md
      - api/shell/args.md
      - api/shell/stdin.md
      - api/shell/stdout.md
      - api/shell/stderr.md
      - api/shell/vfs.md
    - shlex: api/shlex.md
    - sqlite:
      - api/sqlite/index.md
      - api/sqlite/busy.md
      - api/sqlite/connection.md
      - api/sqlite/error.md
      - api/sqlite/row.md
      - api/sqlite/rows.md
      - api/sqlite/statement.md
      - api/sqlite/transaction.md
    - ssh: api/ssh.md
    - std:
      - api/std/index.md
      - api/std/abort-error.md
      - api/std/args.md
      - api/std/array.md
      - api/std/bin.md
      - api/std/binbuf.md
      - api/std/bool.md
      - api/std/bytecode-error.md
      - api/std/canceled-error.md
      - api/std/class.md
      - api/std/compile-error.md
      - api/std/concurrency-error.md
      - api/std/cyclic-import-error.md
      - api/std/dict.md
      - api/std/error.md
      - api/std/field-error.md
      - api/std/float.md
      - api/std/fmt.md
      - api/std/fmt-spec.md
      - api/std/fmt-value.md
      - api/std/fmt-param.md
      - api/std/func.md
      - api/std/getter.md
      - api/std/immutable-error.md
      - api/std/import-error.md
      - api/std/index-error.md
      - api/std/int.md
      - api/std/iter.md
      - api/std/iterable.md
      - api/std/iter-stop.md
      - api/std/missing-key-error.md
      - api/std/missing-pos-error.md
      - api/std/nil.md
      - api/std/null.md
      - api/std/overflow-error.md
      - api/std/range.md
      - api/std/record.md
      - api/std/runtime-error.md
      - api/std/set.md
      - api/std/setter.md
      - api/std/sink.md
      - api/std/sinkable.md
      - api/std/sink-stop.md
      - api/std/state-error.md
      - api/std/static.md
      - api/std/str.md
      - api/std/strbuf.md
      - api/std/sym.md
      - api/std/timed-out-error.md
      - api/std/tuple.md
      - api/std/type.md
      - api/std/type-error.md
      - api/std/unexpected-key-error.md
      - api/std/unexpected-pos-error.md
      - api/std/unsupported-error.md
      - api/std/value.md
      - api/std/value-error.md
      - api/std/zero-div-error.md
    - strand:
      - api/strand/index.md
      - api/strand/key.md
      - api/strand/receiver.md
      - api/strand/resource.md
      - api/strand/sender.md
      - api/strand/strand.md
      - api/strand/stream.md
    - sudo: api/sudo.md
    - sys:
      - api/sys/index.md
      - api/sys/addr-in-use-error.md
      - api/sys/addr-not-available-error.md
      - api/sys/already-exists-error.md
      - api/sys/argument-list-too-long-error.md
      - api/sys/broken-pipe-error.md
      - api/sys/connection-aborted-error.md
      - api/sys/connection-refused-error.md
      - api/sys/connection-reset-error.md
      - api/sys/cpuinfo.md
      - api/sys/crosses-devices-error.md
      - api/sys/deadlock-error.md
      - api/sys/directory-not-empty-error.md
      - api/sys/error.md
      - api/sys/error-code.md
      - api/sys/executable-file-busy-error.md
      - api/sys/file-too-large-error.md
      - api/sys/host-unreachable-error.md
      - api/sys/interrupted-error.md
      - api/sys/invalid-data-error.md
      - api/sys/invalid-filename-error.md
      - api/sys/invalid-input-error.md
      - api/sys/is-a-directory-error.md
      - api/sys/network-down-error.md
      - api/sys/network-unreachable-error.md
      - api/sys/not-a-directory-error.md
      - api/sys/not-connected-error.md
      - api/sys/not-found-error.md
      - api/sys/not-seekable-error.md
      - api/sys/osinfo.md
      - api/sys/out-of-memory-error.md
      - api/sys/permission-denied-error.md
      - api/sys/quota-exceeded-error.md
      - api/sys/read-only-filesystem-error.md
      - api/sys/resource-busy-error.md
      - api/sys/stale-network-file-handle-error.md
      - api/sys/storage-full-error.md
      - api/sys/timed-out-error.md
      - api/sys/too-many-links-error.md
      - api/sys/unexpected-eof-error.md
      - api/sys/unsupported-error.md
      - api/sys/would-block-error.md
      - api/sys/write-zero-error.md
    - sys.linux:
      - api/sys/linux/index.md
      - api/sys/linux/errno.md
    - sys.freebsd:
      - api/sys/freebsd/index.md
      - api/sys/freebsd/errno.md
    - sys.macos:
      - api/sys/macos/index.md
      - api/sys/macos/errno.md
    - sys.unix:
      - api/sys/unix/index.md
      - api/sys/unix/errno.md
    - sys.windows:
      - api/sys/windows/index.md
      - api/sys/windows/win-error.md
    - systemd: api/systemd.md
    - tar:
      - api/tar/index.md
      - api/tar/entry.md
      - api/tar/entry-writer.md
      - api/tar/reader.md
      - api/tar/writer.md
    - term:
      - api/term/index.md
      - api/term/console.md
      - api/term/geometry.md
      - api/term/sink-console.md
      - api/term/style.md
      - api/term/text.md
    - test:
      - api/test/index.md
      - api/test/skip.md
      - api/test/test-info.md
    - time:
      - api/time/index.md
      - api/time/date.md
      - api/time/datetime.md
      - api/time/duration.md
      - api/time/month.md
      - api/time/weekday.md
    - toml: api/toml.md
    - toolbx: api/toolbx.md
    - transfer: api/transfer.md
    - url:
      - api/url/index.md
      - api/url/url.md
    - uuid:
      - api/uuid/index.md
      - api/uuid/guid.md
      - api/uuid/uuid.md
    - winnet:
      - api/winnet/index.md
      - api/winnet/account-policy.md
      - api/winnet/connection.md
      - api/winnet/connection-info.md
      - api/winnet/group.md
      - api/winnet/group-info.md
      - api/winnet/join-status.md
      - api/winnet/machine-info.md
      - api/winnet/server-type.md
      - api/winnet/share.md
      - api/winnet/share-info.md
      - api/winnet/user.md
      - api/winnet/user-flags.md
      - api/winnet/user-info.md
    - winreg:
      - api/winreg/index.md
      - api/winreg/access-mask.md
      - api/winreg/key.md
      - api/winreg/link-target.md
      - api/winreg/value.md
    - winscm:
      - api/winscm/index.md
      - api/winscm/manager-access-mask.md
      - api/winscm/notify-mask.md
      - api/winscm/sc-manager.md
      - api/winscm/service.md
      - api/winscm/service-access-mask.md
      - api/winscm/service-config.md
      - api/winscm/service-controls-accepted.md
      - api/winscm/service-info.md
      - api/winscm/service-type.md
      - api/winscm/status.md
    - wsl: api/wsl.md
    - xdg: api/xdg.md
    - xml:
      - api/xml/index.md
      - api/xml/attr.md
      - api/xml/node.md
    - yaml: api/yaml.md
    - zip:
      - api/zip/index.md
      - api/zip/archive.md
      - api/zip/entry.md
      - api/zip/file.md
  - Rust API: rust-api.md
