[package]
name = "dolang-private-regression"
version = "0.1.0"
description = "Regression test suite for the Do language crates."
edition = "2024"
license.workspace = true
repository.workspace = true
rust-version.workspace = true
publish = false


[lib]
test = false
doctest = false


[dependencies.dolang]
workspace = true


[dependencies.dolang-runtime]
workspace = true


[dependencies.dolang-private-test]
workspace = true


[dependencies.futures]
workspace = true


[build-dependencies.dolang-private-build]
workspace = true
