[package]
name = "dolang-wasm"
version = "0.1.0"
edition = "2024"
license.workspace = true
rust-version.workspace = true
publish = false

[lib]
crate-type = ["cdylib", "rlib"]

[dependencies]
dolang.workspace = true
dolang-ext-base64.workspace = true
dolang-ext-compile.workspace = true
dolang-ext-digest.workspace = true
dolang-ext-glob.workspace = true
dolang-ext-json.workspace = true
dolang-ext-load.workspace = true
dolang-ext-rand.workspace = true
dolang-ext-regex.workspace = true
dolang-ext-toml.workspace = true
dolang-ext-url.workspace = true
dolang-ext-uuid.workspace = true
dolang-ext-xml.workspace = true
dolang-ext-yaml.workspace = true
js-sys = "0.3"
serde = { workspace = true, features = ["derive"] }
serde-wasm-bindgen = "0.6"
wasm-bindgen = "=0.2.128"
wasm-bindgen-futures = "0.4"

[target.'cfg(target_family = "wasm")'.dev-dependencies]
wasm-bindgen-test = "0.3"

[target.'cfg(all(target_arch = "wasm32", target_os = "unknown"))'.dependencies]
getrandom = { version = "0.4", features = ["wasm_js"] }
uuid = { workspace = true, features = ["js"] }
