[package]
name = "dolang-winterop"
version = "0.1.1"
description = "Portable Windows security-descriptor/SID/GUID primitives."
edition = "2024"
license.workspace = true
repository.workspace = true
rust-version.workspace = true


[lib]
test = true


[dependencies.bitflags]
workspace = true
features = ["serde"]


[dependencies.phf]
workspace = true
features = ["macros"]


[dependencies.rand]
workspace = true


[dependencies.serde]
workspace = true
features = ["derive"]


[target.'cfg(windows)'.dependencies.windows-sys]
workspace = true
features = [
  "Win32_Foundation",
  "Win32_Security",
  "Win32_System_LibraryLoader",
  "Win32_System_Threading",
]


[target.'cfg(windows)'.dependencies.futures]
workspace = true


[dev-dependencies.postcard]
workspace = true
features = ["use-std"]
