[package]
name = "dolang-lsp"
version = "0.1.1"
description = "Language Server Protocol implementation for the Do language."
edition = "2024"
license.workspace = true
repository.workspace = true
rust-version.workspace = true


[lints.rust]
unexpected_cfgs = { level = "warn", check-cfg = ["cfg(asan)"] }


[dependencies.backtrace]
version = "0.3"


[dependencies.dirs]
version = "6.0.0"


[dependencies.env_logger]
version = "0.11.8"


[dependencies.log]
version = "0.4.28"


[dependencies.toml]
workspace = true
features = ["parse"]

[dependencies.mimalloc]
workspace = true


[dependencies.tokio]
workspace = true
features = ["macros", "rt", "rt-multi-thread", "io-std", "time"]


[dependencies.tower-lsp-server]
version = "0.23.0"


[dependencies.dolang-compile]
workspace = true


[build-dependencies.serde]
workspace = true
features = ["derive"]


[build-dependencies.serde_json]
workspace = true


[dev-dependencies.futures]
workspace = true


[dev-dependencies.serde]
workspace = true


[dev-dependencies.serde_json]
workspace = true


[dev-dependencies.tower]
version = "0.5"
