//! Validates and embeds the typelib directory generated by `dodo install`.

use std::{env, fmt::Write as _, fs, path::Path};

use dolang_compile::typeck::Typelib;

pub(crate) fn generate() {
    println!("cargo:rerun-if-env-changed=DOLANG_LSP_TYPELIB_DIR");
    let table = match env::var_os("DOLANG_LSP_TYPELIB_DIR") {
        Some(dir) => render(Some(Path::new(&dir))),
        None => render(None),
    };
    let out = env::var_os("OUT_DIR").expect("OUT_DIR is always set by cargo");
    fs::write(Path::new(&out).join("typelib_index_data.rs"), table)
        .expect("failed to write generated typelib index");
}

pub(crate) fn render(dir: Option<&Path>) -> String {
    let mut entries = Vec::new();
    if let Some(dir) = dir {
        let dir = dir.canonicalize().unwrap_or_else(|err| {
            panic!(
                "failed to read DOLANG_LSP_TYPELIB_DIR {}: {err}",
                dir.display()
            )
        });
        println!("cargo:rerun-if-changed={}", dir.display());
        for entry in fs::read_dir(&dir)
            .unwrap_or_else(|err| panic!("failed to read {}: {err}", dir.display()))
        {
            let path = entry
                .expect("failed to read typelib directory entry")
                .path();
            if path.extension().is_none_or(|ext| ext != "dolt") {
                continue;
            }
            println!("cargo:rerun-if-changed={}", path.display());
            let bytes = fs::read(&path)
                .unwrap_or_else(|err| panic!("failed to read {}: {err}", path.display()));
            let typelib = Typelib::read(&bytes)
                .unwrap_or_else(|err| panic!("failed to decode {}: {err}", path.display()));
            let name = path
                .file_stem()
                .and_then(|name| name.to_str())
                .unwrap_or_else(|| panic!("invalid typelib filename: {}", path.display()));
            assert_eq!(
                name,
                typelib.module(),
                "module mismatch in {}",
                path.display()
            );
            entries.push((name.to_owned(), path));
        }
    }
    entries.sort_by(|a, b| a.0.cmp(&b.0));
    let mut out = String::from("pub(crate) static ENTRIES: &[(&str, &[u8])] = &[\n");
    for (name, path) in entries {
        writeln!(out, "    ({name:?}, include_bytes!({path:?})),")
            .expect("writing to a String cannot fail");
    }
    out.push_str("];\n");
    out
}
