[package]
name = "dolang-private-bundle"
version = "0.1.1"
description = "Build script helpers for bundling Do bytecode resources."
edition = "2024"
license.workspace = true
repository.workspace = true
rust-version.workspace = true


[lib]
test = false
doctest = false


[dependencies.dolang]
workspace = true


[dependencies.dolang-ext-shell]
workspace = true


[dependencies.annotate-snippets]
workspace = true

[features]
debug = ["dolang/debug"]
