[package]
name = "dolang-shell"
version = "0.1.1"
description = "Stock command-line shell binary for the Do language."
edition = "2024"
license.workspace = true
repository.workspace = true
rust-version.workspace = true
autobins = false


[lints.rust]
unexpected_cfgs = { level = "warn", check-cfg = ["cfg(asan)"] }


[[bin]]
name = "dolang"
path = "src/main.rs"


[features]
default = [
  "base64",
  "digest",
  "json",
  "regex",
  "glob",
  "http",
  "http_mock",
  "zip",
  "tar",
  "sqlite",
  "xml",
  "yaml",
  "progress",
  "rand",
  "toml",
  "patch",
  "winreg",
  "winscm",
  "winnet",
]
debug = ["dolang-shell-main/debug"]
base64 = ["dep:dolang-ext-base64"]
digest = ["dep:dolang-ext-digest"]
json = [
  "dep:dolang-ext-json",
  "dolang-ext-http?/json",
  "dolang-ext-http-mock?/json",
]
regex = ["dep:dolang-ext-regex"]
glob = ["dep:dolang-ext-glob"]
url = ["dep:dolang-ext-url"]
http = ["dep:dolang-ext-http", "url"]
http_mock = ["dep:dolang-ext-http-mock", "url"]
zip = ["dep:dolang-ext-zip"]
tar = ["dep:dolang-ext-tar"]
sqlite = ["dep:dolang-ext-sqlite"]
xml = ["dep:dolang-ext-xml"]
yaml = ["dep:dolang-ext-yaml"]
progress = ["dep:dolang-ext-progress"]
rand = ["dep:dolang-ext-rand"]
toml = ["dep:dolang-ext-toml"]
patch = ["dep:dolang-ext-patch"]
winreg = ["dep:dolang-ext-winreg", "dolang-shell-vfs/winreg"]
winscm = ["dep:dolang-ext-winscm", "dolang-shell-vfs/winscm"]
winnet = ["dep:dolang-ext-winnet", "dolang-shell-vfs/winnet"]


[dependencies.dolang-shell-vfs]
workspace = true


[dependencies.mimalloc]
workspace = true


[dependencies.dolang-shell-main]
workspace = true


[dependencies.dolang-shell-modules]
workspace = true


[dependencies.dolang]
workspace = true


[target.'cfg(windows)'.dev-dependencies.dolang-vfs]
workspace = true


[target.'cfg(windows)'.dev-dependencies.tokio]
workspace = true
features = ["io-util", "macros", "net", "process", "rt-multi-thread", "time"]

[dependencies.dolang-ext-digest]
workspace = true
optional = true


[dependencies.dolang-ext-base64]
workspace = true
optional = true


[dependencies.dolang-ext-compile]
workspace = true


[dependencies.dolang-ext-load]
workspace = true


[dependencies.dolang-ext-json]
workspace = true
optional = true


[dependencies.dolang-ext-regex]
workspace = true
optional = true


[dependencies.dolang-ext-glob]
workspace = true
optional = true


[dependencies.dolang-ext-http]
workspace = true
optional = true


[dependencies.dolang-ext-http-mock]
workspace = true
optional = true


[dependencies.dolang-ext-url]
workspace = true
optional = true


[dependencies.dolang-ext-zip]
workspace = true
optional = true


[dependencies.dolang-ext-tar]
workspace = true
optional = true


[dependencies.dolang-ext-sqlite]
workspace = true
optional = true


[dependencies.dolang-ext-xml]
workspace = true
optional = true


[dependencies.dolang-ext-yaml]
workspace = true
optional = true


[dependencies.dolang-ext-progress]
workspace = true
optional = true


[dependencies.dolang-ext-rand]
workspace = true
optional = true


[dependencies.dolang-ext-toml]
workspace = true
optional = true


[dependencies.dolang-ext-patch]
workspace = true
optional = true


[dependencies.dolang-ext-winreg]
workspace = true
optional = true


[dependencies.dolang-ext-winscm]
workspace = true
optional = true


[dependencies.dolang-ext-winnet]
workspace = true
optional = true


[build-dependencies.dolang-private-bundle]
workspace = true
