[package]
name = "dolang-bytecode"
version = "0.1.1"
description = "Bytecode format and verification for the Do language."
edition = "2024"
license.workspace = true
repository.workspace = true
rust-version.workspace = true


[dependencies.postcard]
workspace = true
features = ["use-std"]


[dependencies.serde]
workspace = true
features = ["derive"]


[dependencies.dolang-util]
workspace = true


[features]
default = []
debug = ["dolang-util/debug"]
