[package]
name = "dolang-ext-zip"
version = "0.1.1"
description = "ZIP archive extension for the Do language."
edition = "2024"
license.workspace = true
repository.workspace = true
rust-version.workspace = true


[lib]
test = false
doctest = false


[dependencies.futures-lite]
version = "2.6"
default-features = false
features = ["std"]


[dependencies.tokio]
workspace = true
features = ["fs", "io-util", "rt"]


[dependencies.tokio-util]
version = "0.7"
features = ["compat"]

[dependencies.async_zip]
package = "astral_async_zip"
version = "0.0.21"
default-features = false
features = ["deflate", "jiff", "tokio", "zstd"]


[dependencies.jiff]
version = "0.2"


[dependencies.dolang]
workspace = true


[dependencies.dolang-ext-shell]
workspace = true


[dependencies.dolang-ext-time]
workspace = true


[dependencies.dolang-vfs]
workspace = true
