[package]
name = "dolang-vfs-winnet"
version = "0.1.1"
description = "Windows NetAPI VFS bindings for dolang-vfs."
edition = "2024"
license.workspace = true
repository.workspace = true
rust-version.workspace = true


[lib]
test = true
doctest = false


[dependencies.bitflags]
workspace = true
features = ["serde"]


[dependencies.serde]
workspace = true
features = ["derive"]


[dependencies.dolang-vfs]
workspace = true


[dependencies.dolang-winterop]
workspace = true


[dependencies.tokio]
workspace = true
features = ["rt"]


[target.'cfg(windows)'.dependencies.windows-sys]
workspace = true
features = [
  "Win32_Foundation",
  "Win32_NetworkManagement_NetManagement",
  "Win32_NetworkManagement_WNet",
  "Win32_Security",
  "Win32_Security_Authentication_Identity",
  "Win32_Security_Credentials",
  "Win32_Storage_FileSystem",
]


[dev-dependencies.postcard]
workspace = true
features = ["use-std"]


[dev-dependencies.tokio]
workspace = true
features = ["rt-multi-thread", "macros", "io-util"]


[dev-dependencies.tempfile]
workspace = true
