[package]
name = "dolang-shell-modules"
version = "0.1.1"
description = "Stock embedded Do modules for the shell."
edition = "2024"
license.workspace = true
repository.workspace = true
rust-version.workspace = true


[lib]
test = false
doctest = false


[build-dependencies.dolang-private-bundle]
workspace = true


[build-dependencies.dolang-ext-shell]
workspace = true

[features]
debug = ["dolang-private-bundle/debug"]
