[package]
name = "dolang-ext-shell"
version = "0.1.1"
description = "Shell, process, and filesystem extension for the Do language."
edition = "2024"
license.workspace = true
repository.workspace = true
rust-version.workspace = true


[lib]
doctest = false


[features]
default = []
debug = ["dolang/debug"]


[dependencies.linkme]
workspace = true


[dependencies.phf]
workspace = true
features = ["macros"]


[dependencies.futures]
workspace = true


[dependencies.rand]
workspace = true


[dependencies.bstr]
workspace = true


[dependencies.bytes]
workspace = true


[dependencies.shlex]
version = "2.0"


[dependencies.anstyle]
workspace = true


[dependencies.console]
workspace = true


[dependencies.unicode-segmentation]
workspace = true


[dependencies.unicode-width]
workspace = true

[dependencies.tokio]
workspace = true
features = [
  "macros",
  "rt",
  "fs",
  "process",
  "io-util",
  "sync",
  "io-std",
  "time",
]


[dependencies.dolang]
workspace = true


[dependencies.dolang-ext-compile]
workspace = true
features = ["diagnostic-rendering"]


[dependencies.dolang-vfs]
workspace = true


[dependencies.dolang-winterop]
workspace = true


[dependencies.dolang-ext-uuid]
workspace = true


[dependencies.dolang-ext-time]
workspace = true


[target.'cfg(unix)'.dependencies.nix]
workspace = true
features = ["dir", "fs", "signal", "term", "user"]


[target.'cfg(unix)'.dependencies.libc]
workspace = true


[target.'cfg(windows)'.dependencies.dunce]
workspace = true
