[package]
name = "dolang-ext-winnet"
version = "0.1.1"
description = "Windows NetAPI bindings for the Do language."
edition = "2024"
license.workspace = true
repository.workspace = true
rust-version.workspace = true


[lib]
test = false
doctest = false


[dependencies.dolang]
workspace = true


[dependencies.dolang-ext-shell]
workspace = true


[dependencies.dolang-ext-time]
workspace = true


[dependencies.dolang-vfs]
workspace = true


[dependencies.dolang-vfs-winnet]
workspace = true


[dependencies.dolang-winterop]
workspace = true
