[package]
name = "dolang-vfs"
version = "0.1.1"
description = "Virtual filesystem library and extension interface for Do language integrations."
edition = "2024"
license.workspace = true
repository.workspace = true
rust-version.workspace = true


[lib]
test = true


[lints.rust]
unexpected_cfgs = { level = "warn", check-cfg = ["cfg(docsrs)"] }


[dependencies.bitflags]
workspace = true
features = ["serde"]


[dependencies.bytes]
workspace = true


[dependencies.tokio]
workspace = true
features = [
  "io-std",
  "io-util",
  "sync",
  "rt-multi-thread",
  "rt",
  "macros",
  "fs",
  "net",
  "process",
  "time",
]


[dependencies.wax]
workspace = true
features = ["walk"]


[dependencies.serde]
workspace = true
features = ["derive"]


[dependencies.which]
version = "8.0"


[dependencies.dolang-rpc]
workspace = true


[dependencies.dolang-winterop]
workspace = true


[dependencies.typed-path]
workspace = true


[dependencies.linkme]
workspace = true


[dependencies.erased-serde]
version = "0.4"


[dependencies.thiserror]
workspace = true


[dependencies.uuid]
workspace = true
features = ["serde", "v4"]


[target.'cfg(windows)'.dependencies.dunce]
workspace = true


[target.'cfg(windows)'.dependencies.rand]
workspace = true


[target.'cfg(windows)'.dependencies.tokio]
workspace = true
features = ["signal"]


[target.'cfg(windows)'.dependencies.windows-sys]
workspace = true
features = [
  "Wdk_Storage_FileSystem",
  "Win32_Foundation",
  "Win32_Security",
  "Win32_Security_Authorization",
  "Win32_Storage_FileSystem",
  "Win32_System_Com",
  "Win32_System_Diagnostics_Debug",
  "Win32_System_Diagnostics_ToolHelp",
  "Win32_System_Environment",
  "Win32_System_IO",
  "Win32_System_Ioctl",
  "Win32_System_JobObjects",
  "Win32_System_Kernel",
  "Win32_System_LibraryLoader",
  "Win32_System_Pipes",
  "Win32_System_Registry",
  "Win32_System_SystemServices",
  "Win32_System_Threading",
  "Win32_UI_Shell",
  "Win32_UI_WindowsAndMessaging",
]


[dev-dependencies.tempfile]
workspace = true


[dev-dependencies.postcard]
workspace = true
features = ["use-std"]


[dev-dependencies.criterion]
workspace = true
features = ["async_tokio"]


[target.'cfg(unix)'.dependencies.tokio]
workspace = true
features = ["process", "time", "signal"]


[target.'cfg(unix)'.dependencies.libc]
workspace = true


[target.'cfg(unix)'.dependencies.nix]
workspace = true
features = ["dir", "fs", "ioctl", "user", "socket"]


[target.'cfg(unix)'.dev-dependencies.futures]
workspace = true

[[bench]]
name = "remote_file"
harness = false
