[package]
name = "dolang-shell-vfs"
version = "0.1.1"
description = "Shell VFS daemon for Do language integrations."
edition = "2024"
license.workspace = true
repository.workspace = true
rust-version.workspace = true
autobins = false


[lints.rust]
unexpected_cfgs = { level = "warn", check-cfg = ["cfg(asan)"] }


[[bin]]
name = "dolang-vfs"
path = "src/bin/dolang-vfs.rs"
test = false


[features]
default = ["winreg", "winscm", "winnet"]
winreg = ["dep:dolang-vfs-winreg"]
winscm = ["dep:dolang-vfs-winscm"]
winnet = ["dep:dolang-vfs-winnet"]


[dependencies.base64]
workspace = true


[dependencies.dolang-rpc]
workspace = true


[dependencies.dolang-vfs]
workspace = true


[dependencies.dolang-vfs-winreg]
workspace = true
optional = true


[dependencies.dolang-vfs-winscm]
workspace = true
optional = true


[dependencies.dolang-vfs-winnet]
workspace = true
optional = true


[dependencies.tokio]
workspace = true
features = ["io-std", "io-util", "macros", "net", "rt", "signal"]

[dependencies.mimalloc]
workspace = true


[target.'cfg(unix)'.dependencies.libc]
workspace = true


[target.'cfg(unix)'.dependencies.nix]
workspace = true
features = ["fs", "user"]


[target.'cfg(windows)'.dependencies.windows-sys]
workspace = true
features = [
  "Win32_Foundation",
  "Win32_System_Com",
  "Win32_System_Environment",
  "Win32_System_Registry",
  "Win32_UI_Shell",
]


[dev-dependencies.tempfile]
workspace = true


[dev-dependencies.tokio]
workspace = true
features = [
  "fs",
  "io-util",
  "macros",
  "net",
  "process",
  "rt-multi-thread",
  "sync",
  "time",
]


[target.'cfg(unix)'.dev-dependencies.futures]
workspace = true


[target.'cfg(unix)'.dev-dependencies.libc]
workspace = true
