[package]
name = "dolang-shell-vfs"
version = "0.1.1"
description = "Shell VFS daemon for Do language integrations."
edition = "2024"
license.workspace = true
repository.workspace = true
rust-version.workspace = true
autobins = false

[[bin]]
name = "dolang-vfs"
path = "src/main.rs"
test = false

[features]
default = ["winreg", "winscm"]
winreg = ["dep:dolang-vfs-winreg"]
winscm = ["dep:dolang-vfs-winscm"]

[dependencies]
dolang-vfs = { path = "../dolang-vfs", version = "0.1.1" }
dolang-vfs-winreg = { path = "../dolang-vfs-winreg", version = "0.1.0", optional = true }
dolang-vfs-winscm = { path = "../dolang-vfs-winscm", version = "0.1.0", optional = true }

[dev-dependencies]
base64 = "0.22.1"
serde = { version = "1.0", features = ["derive"] }
tempfile = "3"
postcard = { version = "1.1.3", features = ["use-std"] }
tokio = { version = "1.48.0", features = ["fs", "io-util", "macros", "net", "process", "rt-multi-thread", "sync", "time"] }
dolang-winterop = { path = "../dolang-winterop", version = "0.1.0" }

[target.'cfg(unix)'.dev-dependencies]
futures = "0.3"
libc = "0.2"
nix = { version = "0.31", features = ["user"] }

[target.'cfg(windows)'.dev-dependencies]
windows-sys = { version = "0.61", features = ["Win32_Foundation", "Win32_Security", "Win32_Storage_FileSystem", "Win32_System_LibraryLoader", "Win32_System_Threading"] }
