[package]
name = "dolang-ext-digest"
version = "0.1.1"
description = "Digest and hashing extension for the Do language."
edition = "2024"
license.workspace = true
repository.workspace = true
rust-version.workspace = true


[lib]
test = false
doctest = false


[dependencies.blake3]
workspace = true


[dependencies.digest]
version = "0.11.2"


[dependencies.md-5]
version = "0.11.0"


[dependencies.sha1]
version = "0.11.0"


[dependencies.sha2]
version = "0.11.0"

[dependencies.dolang]
workspace = true
