#!/usr/bin/env python3
"""Generate platform system error-code name tables.

The source documents are intentionally supplied by the caller rather than
downloaded here. This keeps regeneration explicit and makes it possible to
verify the pinned input hashes recorded in the generated file.

Current source revisions:
- Linux UAPI asm-generic/errno-base.h and asm-generic/errno.h
- apple-oss-distributions/xnu bsd/sys/errno.h at f6217f891ac0bb64f3d375211650a4c1ff8ca1ea
- MS-ERREF revision 23.0 DOCX, published 2024-11-19
"""

import argparse
import hashlib
import re
import sys
import xml.etree.ElementTree as ET
import zipfile
from pathlib import Path


DEFINE = re.compile(r"^\s*#\s*define\s+(E[A-Z0-9_]+)\s+([^\s/]+)", re.MULTILINE)
NUMBER = re.compile(r"^\(?([0-9]+)\)?$")
WIN32 = re.compile(r"^(0x[0-9A-Fa-f]{8})([A-Z][A-Z0-9_]+)$")
WORD_NS = "{http://schemas.openxmlformats.org/wordprocessingml/2006/main}"


def digest(path: Path) -> str:
    return hashlib.sha256(path.read_bytes()).hexdigest()


def parse_errno(paths: list[Path]) -> list[tuple[int, str]]:
    definitions: dict[str, str] = {}
    order: list[str] = []
    for path in paths:
        for name, expression in DEFINE.findall(path.read_text()):
            if name not in definitions:
                order.append(name)
            definitions[name] = expression

    resolved: dict[str, int] = {}

    def resolve(name: str, stack: set[str]) -> int | None:
        if name in resolved:
            return resolved[name]
        if name in stack:
            raise ValueError(f"cyclic errno alias involving {name}")
        expression = definitions.get(name)
        if expression is None:
            return None
        match = NUMBER.match(expression)
        if match:
            value = int(match.group(1))
        elif expression in definitions:
            value = resolve(expression, stack | {name})
            if value is None:
                return None
        else:
            return None
        resolved[name] = value
        return value

    # Numeric definitions are canonical; alias-only names do not replace them.
    result: dict[int, str] = {}
    for name in order:
        if not NUMBER.match(definitions[name]):
            continue
        value = resolve(name, set())
        if value is not None:
            result.setdefault(value, name)
    return sorted(result.items())


def parse_windows(path: Path) -> list[tuple[int, str]]:
    with zipfile.ZipFile(path) as archive:
        root = ET.fromstring(archive.read("word/document.xml"))

    body = root.find(WORD_NS + "body")
    if body is None:
        raise ValueError("MS-ERREF DOCX has no document body")

    active = False
    result: dict[int, str] = {}
    for element in body:
        text = "".join(node.text or "" for node in element.iter(WORD_NS + "t"))
        if element.tag == WORD_NS + "p" and text == "Win32 Error Codes":
            active = True
            continue
        if element.tag == WORD_NS + "p" and text == "NTSTATUS":
            active = False
        if not active or element.tag != WORD_NS + "tbl":
            continue
        for row in element.iter(WORD_NS + "tr"):
            cells = [
                "".join(node.text or "" for node in cell.iter(WORD_NS + "t"))
                for cell in row.findall(WORD_NS + "tc")
            ]
            if not cells:
                continue
            match = WIN32.match(cells[0])
            if match:
                value = int(match.group(1), 16)
                result.setdefault(value, match.group(2))

    if not result:
        raise ValueError("no Win32 codes found in MS-ERREF DOCX")
    return sorted(result.items())


def rust_table(name: str, values: list[tuple[int, str]], value_type: str) -> str:
    rows = "\n".join(f'    ({value}, "{symbol}"),' for value, symbol in values)
    return f"pub(crate) static {name}: &[({value_type}, &str)] = &[\n{rows}\n];\n"


def generate(args: argparse.Namespace) -> str:
    linux = parse_errno(args.linux)
    macos = parse_errno(args.macos)
    windows = parse_windows(args.windows)
    sources = [*args.linux, *args.macos, args.windows]
    provenance = "\n".join(f"// {path.name}: sha256:{digest(path)}" for path in sources)
    return (
        "// @generated by tools/gen_system_error_codes.py; do not edit.\n"
        "// MS-ERREF revision 23.0 (2024-11-19).\n"
        f"{provenance}\n\n"
        + rust_table("LINUX_ERRNO", linux, "i32")
        + "\n"
        + rust_table("MACOS_ERRNO", macos, "i32")
        + "\n"
        + rust_table("WIN_ERROR", windows, "u32")
    )


def main() -> int:
    parser = argparse.ArgumentParser()
    parser.add_argument("--linux", type=Path, action="append", required=True)
    parser.add_argument("--macos", type=Path, action="append", required=True)
    parser.add_argument("--windows", type=Path, required=True)
    parser.add_argument("--output", type=Path, required=True)
    parser.add_argument("--check", action="store_true")
    args = parser.parse_args()

    generated = generate(args)
    if args.check:
        if args.output.read_text() != generated:
            print(f"generated output is stale: {args.output}", file=sys.stderr)
            return 1
    else:
        args.output.parent.mkdir(parents=True, exist_ok=True)
        args.output.write_text(generated)
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
