[package]
name = "dolang-ext-http-mock"
version = "0.1.1"
description = "HTTP mock server extension for the Do language."
edition = "2024"
license.workspace = true
repository.workspace = true
rust-version.workspace = true


[lib]
test = false
doctest = false


[features]
default = ["json"]
json = ["dep:dolang-ext-json"]


[dependencies.bstr]
workspace = true


[dependencies.futures]
workspace = true


[dependencies.http]
version = "1"


[dependencies.httpdate]
workspace = true


[dependencies.regex]
workspace = true


[dependencies.url]
workspace = true

[dependencies.tokio]
workspace = true
features = ["rt", "sync"]


[dependencies.wiremock]
version = "0.6"


[dependencies.dolang-ext-json]
workspace = true
optional = true


[dependencies.dolang-ext-url]
workspace = true


[dependencies.dolang-ext-time]
workspace = true


[dependencies.dolang]
workspace = true
