[package]
name = "dolang-vfs-winreg"
version = "0.1.1"
description = "Windows registry VFS extension for dolang-vfs."
edition = "2024"
license.workspace = true
repository.workspace = true
rust-version.workspace = true


[lib]
test = true
doctest = false


[dependencies.serde]
workspace = true
features = ["derive"]


[dependencies.dolang-vfs]
workspace = true


[dependencies.dolang-winterop]
workspace = true


[dependencies.tokio]
workspace = true
features = ["rt"]


[target.'cfg(windows)'.dependencies.windows-sys]
workspace = true
features = ["Win32_Foundation", "Win32_Security", "Win32_System_Registry"]


[dev-dependencies.tokio]
workspace = true
features = ["rt-multi-thread", "macros", "io-util"]


[dev-dependencies.tempfile]
workspace = true
