[package]
name = "dolang-runtime"
version = "0.1.1"
description = "Virtual machine and runtime for the Do language."
edition = "2024"
license.workspace = true
repository.workspace = true
rust-version.workspace = true


[dependencies.bitflags]
workspace = true


[dependencies.bitvec]
workspace = true


[dependencies.bstr]
workspace = true


[dependencies.futures]
workspace = true


[dependencies.hex]
version = "0.4.3"


[dependencies.unicode-segmentation]
workspace = true

[dependencies.dolang-util]
workspace = true


[dependencies.dolang-bytecode]
workspace = true


[dev-dependencies.dolang-compile]
workspace = true


[features]
default = []
debug = ["dolang-util/debug", "dolang-bytecode/debug"]
